-- Durable sandbox control plane. This additive schema is intentionally separate from invocation runtime tables.
CREATE TABLE IF NOT EXISTS sandbox_image_recipes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name TEXT NOT NULL, slug TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', created_by TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, UNIQUE(id,tenant_id));
CREATE UNIQUE INDEX IF NOT EXISTS sandbox_image_recipes_active_slug_unique ON sandbox_image_recipes(tenant_id,slug) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS sandbox_recipe_request_keys (tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, recipe_id TEXT NOT NULL REFERENCES sandbox_image_recipes(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS sandbox_profile_versions (id TEXT PRIMARY KEY, profile_family TEXT NOT NULL, name TEXT NOT NULL, version TEXT NOT NULL, vcpu INT NOT NULL CHECK(vcpu>0), memory_mb INT NOT NULL CHECK(memory_mb>0), mutable_disk_layout JSONB NOT NULL, staging_overhead_bytes BIGINT NOT NULL DEFAULT 0 CHECK(staging_overhead_bytes>=0), runtime_overhead JSONB NOT NULL DEFAULT '{}', machine_config JSONB NOT NULL, device_topology JSONB NOT NULL, architecture_constraints JSONB NOT NULL DEFAULT '{}', status TEXT NOT NULL CHECK(status IN('active','unavailable','retired')), canonical_document JSONB NOT NULL, document_digest TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), retired_at TIMESTAMPTZ, UNIQUE(profile_family,version));
CREATE TABLE IF NOT EXISTS sandbox_image_recipe_versions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, recipe_id TEXT NOT NULL, version_number INT NOT NULL CHECK(version_number>0), schema_version TEXT NOT NULL, document JSONB NOT NULL, document_digest TEXT NOT NULL, resolved_base_digest TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN('queued','building','ready','failed','retired')), failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), UNIQUE(recipe_id,version_number), FOREIGN KEY(recipe_id,tenant_id) REFERENCES sandbox_image_recipes(id,tenant_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sandbox_image_recipe_profile_artifacts (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, recipe_version_id TEXT NOT NULL, profile_version_id TEXT NOT NULL REFERENCES sandbox_profile_versions(id), artifact_ref TEXT NOT NULL, artifact_digest TEXT NOT NULL, artifact_size BIGINT NOT NULL CHECK(artifact_size>=0), vm_restore_descriptor_digest TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN('queued','building','ready','failed')), failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(recipe_version_id,profile_version_id), FOREIGN KEY(recipe_version_id,tenant_id) REFERENCES sandbox_image_recipe_versions(id,tenant_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sandbox_host_lineages (id TEXT PRIMARY KEY, provider TEXT NOT NULL, host_compatibility_key TEXT NOT NULL UNIQUE, host_compatibility_descriptor JSONB NOT NULL, descriptor_digest TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN('active','retired')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), retired_at TIMESTAMPTZ, UNIQUE(id,host_compatibility_key));
CREATE OR REPLACE FUNCTION sandbox_lineage_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id<>OLD.id OR NEW.host_compatibility_key<>OLD.host_compatibility_key OR NEW.host_compatibility_descriptor<>OLD.host_compatibility_descriptor OR NEW.descriptor_digest<>OLD.descriptor_digest OR NEW.provider<>OLD.provider THEN RAISE EXCEPTION 'sandbox host lineage is immutable'; END IF; IF OLD.status='retired' AND NEW.status<>'retired' THEN RAISE EXCEPTION 'sandbox host lineage retirement is monotonic'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS sandbox_lineage_immutable_trigger ON sandbox_host_lineages; CREATE TRIGGER sandbox_lineage_immutable_trigger BEFORE UPDATE ON sandbox_host_lineages FOR EACH ROW EXECUTE FUNCTION sandbox_lineage_immutable();
CREATE TABLE IF NOT EXISTS sandbox_host_pools (id TEXT PRIMARY KEY, name TEXT NOT NULL, provider TEXT NOT NULL, provider_ref TEXT NOT NULL, region TEXT NOT NULL DEFAULT '', availability_zone TEXT NOT NULL DEFAULT '', lineage_id TEXT NOT NULL, host_compatibility_key TEXT NOT NULL, min_hosts INT NOT NULL DEFAULT 0, max_hosts INT NOT NULL, target_hosts INT NOT NULL DEFAULT 0, status TEXT NOT NULL CHECK(status IN('active','draining','retired')), provider_config JSONB NOT NULL DEFAULT '{}', last_observed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(lineage_id,host_compatibility_key) REFERENCES sandbox_host_lineages(id,host_compatibility_key));
CREATE TABLE IF NOT EXISTS sandbox_hosts (id TEXT PRIMARY KEY, pool_id TEXT NOT NULL REFERENCES sandbox_host_pools(id), provider_instance_id TEXT NOT NULL, incarnation BIGINT NOT NULL DEFAULT 1, state TEXT NOT NULL CHECK(state IN('registering','ready','draining','unreachable','terminated')), lineage_id TEXT NOT NULL, host_compatibility_key TEXT NOT NULL, host_compatibility_descriptor JSONB NOT NULL, vm_restore_capabilities JSONB NOT NULL DEFAULT '{}', total_vcpu INT NOT NULL, reserved_vcpu INT NOT NULL DEFAULT 0, total_memory_mb INT NOT NULL, reserved_memory_mb INT NOT NULL DEFAULT 0, total_disk_bytes BIGINT NOT NULL, reserved_disk_bytes BIGINT NOT NULL DEFAULT 0, total_staging_bytes BIGINT NOT NULL DEFAULT 0, reserved_staging_bytes BIGINT NOT NULL DEFAULT 0, agent_version TEXT NOT NULL DEFAULT '', protocol_version TEXT NOT NULL DEFAULT '', boot_id TEXT NOT NULL, heartbeat_sequence BIGINT NOT NULL DEFAULT 0, last_heartbeat_at TIMESTAMPTZ, lease_expires_at TIMESTAMPTZ, drain_deadline TIMESTAMPTZ, failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(lineage_id,host_compatibility_key) REFERENCES sandbox_host_lineages(id,host_compatibility_key), UNIQUE(pool_id,provider_instance_id));
CREATE TABLE IF NOT EXISTS tenant_sandbox_quotas (tenant_id TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE, max_sandboxes INT NOT NULL DEFAULT 0, max_running INT NOT NULL DEFAULT 0, max_vcpu INT NOT NULL DEFAULT 0, max_memory_mb INT NOT NULL DEFAULT 0, max_disk_gb INT NOT NULL DEFAULT 0, max_snapshot_bytes BIGINT NOT NULL DEFAULT 0, checkpoint_interval_seconds INT NOT NULL DEFAULT 300 CHECK(checkpoint_interval_seconds BETWEEN 60 AND 3600));
CREATE TABLE IF NOT EXISTS sandboxes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name TEXT NOT NULL, recipe_version_id TEXT NOT NULL, profile_version_id TEXT NOT NULL REFERENCES sandbox_profile_versions(id), vm_restore_descriptor_digest TEXT NOT NULL, desired_state TEXT NOT NULL CHECK(desired_state IN('running','stopped','deleted')), observed_state TEXT NOT NULL CHECK(observed_state IN('pending','awaiting_capacity','provisioning','bootstrapping','restoring','running','snapshotting','stopping','stopped','recovering','deleting','failed')), generation BIGINT NOT NULL DEFAULT 1, observed_generation BIGINT NOT NULL DEFAULT 0, fence_epoch BIGINT NOT NULL DEFAULT 0, ever_booted BOOLEAN NOT NULL DEFAULT false, current_allocation_id TEXT, latest_snapshot_id TEXT, checkpoint_due_at TIMESTAMPTZ, failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', created_by TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ, UNIQUE(id,tenant_id), FOREIGN KEY(recipe_version_id,tenant_id) REFERENCES sandbox_image_recipe_versions(id,tenant_id));
CREATE TABLE IF NOT EXISTS sandbox_allocations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, sandbox_id TEXT NOT NULL, host_id TEXT NOT NULL REFERENCES sandbox_hosts(id), host_incarnation BIGINT NOT NULL, state TEXT NOT NULL CHECK(state IN('reserved','active','releasing','released','lost')), fence_epoch BIGINT NOT NULL, lease_token_hash TEXT NOT NULL, lease_expires_at TIMESTAMPTZ NOT NULL, reserved_vcpu INT NOT NULL DEFAULT 0, reserved_memory_mb INT NOT NULL DEFAULT 0, reserved_disk_bytes BIGINT NOT NULL DEFAULT 0, reserved_staging_bytes BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), FOREIGN KEY(sandbox_id,tenant_id) REFERENCES sandboxes(id,tenant_id) ON DELETE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS sandbox_one_live_allocation ON sandbox_allocations(sandbox_id) WHERE state IN('reserved','active','releasing');
CREATE TABLE IF NOT EXISTS sandbox_operations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, sandbox_id TEXT, recipe_version_id TEXT, snapshot_id TEXT, retry_of_operation_id TEXT, kind TEXT NOT NULL CHECK(kind IN('recipe_build','create','start','stop','restart','snapshot','restore','recover','delete','snapshot_delete')), state TEXT NOT NULL CHECK(state IN('queued','claimed','dispatched','waiting','succeeded','failed','cancelled')), requested_generation BIGINT NOT NULL DEFAULT 0, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, actor_id TEXT NOT NULL DEFAULT '', actor_type TEXT NOT NULL DEFAULT '', attempt INT NOT NULL DEFAULT 0, max_attempts INT NOT NULL DEFAULT 3, next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(), owner_id TEXT, lease_token_hash TEXT, lease_expires_at TIMESTAMPTZ, deadline_at TIMESTAMPTZ, failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', result JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), UNIQUE(id,tenant_id,sandbox_id), UNIQUE(id,tenant_id,sandbox_id,kind), UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(sandbox_id,tenant_id) REFERENCES sandboxes(id,tenant_id) ON DELETE CASCADE, FOREIGN KEY(recipe_version_id,tenant_id) REFERENCES sandbox_image_recipe_versions(id,tenant_id) ON DELETE CASCADE, CHECK((kind='recipe_build' AND recipe_version_id IS NOT NULL AND sandbox_id IS NULL AND snapshot_id IS NULL) OR (kind<>'recipe_build' AND sandbox_id IS NOT NULL AND recipe_version_id IS NULL)), CHECK((kind IN('restore','snapshot_delete') AND snapshot_id IS NOT NULL) OR (kind='snapshot') OR (kind IN('recipe_build','create','start','stop','restart','recover','delete') AND snapshot_id IS NULL)));
CREATE UNIQUE INDEX IF NOT EXISTS sandbox_one_active_operation ON sandbox_operations(sandbox_id) WHERE state IN('queued','claimed','dispatched','waiting') AND kind<>'recipe_build'; CREATE UNIQUE INDEX IF NOT EXISTS sandbox_one_active_recipe_build ON sandbox_operations(recipe_version_id) WHERE state IN('queued','claimed','dispatched','waiting') AND kind='recipe_build';
ALTER TABLE sandbox_operations DROP CONSTRAINT IF EXISTS sandbox_operations_retry_parent_fk; ALTER TABLE sandbox_operations ADD CONSTRAINT sandbox_operations_retry_parent_fk FOREIGN KEY(retry_of_operation_id,tenant_id,sandbox_id,kind) REFERENCES sandbox_operations(id,tenant_id,sandbox_id,kind);
CREATE TABLE IF NOT EXISTS sandbox_snapshots (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, sandbox_id TEXT NOT NULL, allocation_id TEXT, operation_id TEXT NOT NULL, generation BIGINT NOT NULL, kind TEXT NOT NULL CHECK(kind IN('periodic','manual','stop','drain','recovery')), state TEXT NOT NULL CHECK(state IN('requested','uploading','verifying','ready','failed','deleting','deleted')), lineage_id TEXT NOT NULL, source_host_compatibility_key TEXT NOT NULL, vm_restore_descriptor_digest TEXT NOT NULL, snapshot_compatibility_key TEXT NOT NULL, manifest_version TEXT NOT NULL DEFAULT '1', manifest JSONB NOT NULL DEFAULT '{}', manifest_checksum TEXT NOT NULL DEFAULT '', wrapped_data_key TEXT NOT NULL DEFAULT '', encryption_context_digest TEXT NOT NULL DEFAULT '', total_bytes BIGINT NOT NULL DEFAULT 0, failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), ready_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ, UNIQUE(id,tenant_id), UNIQUE(id,tenant_id,sandbox_id), FOREIGN KEY(sandbox_id,tenant_id) REFERENCES sandboxes(id,tenant_id) ON DELETE CASCADE, FOREIGN KEY(operation_id,tenant_id) REFERENCES sandbox_operations(id,tenant_id));
ALTER TABLE sandboxes DROP CONSTRAINT IF EXISTS sandboxes_latest_snapshot_fk; ALTER TABLE sandboxes ADD CONSTRAINT sandboxes_latest_snapshot_fk FOREIGN KEY(latest_snapshot_id,tenant_id) REFERENCES sandbox_snapshots(id,tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sandbox_operations DROP CONSTRAINT IF EXISTS sandbox_operations_snapshot_tenant_fk; ALTER TABLE sandbox_operations ADD CONSTRAINT sandbox_operations_snapshot_tenant_fk FOREIGN KEY(snapshot_id,tenant_id) REFERENCES sandbox_snapshots(id,tenant_id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE IF NOT EXISTS sandbox_commands (id TEXT PRIMARY KEY, operation_id TEXT NOT NULL REFERENCES sandbox_operations(id), tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, sandbox_id TEXT NOT NULL, allocation_id TEXT NOT NULL REFERENCES sandbox_allocations(id), host_id TEXT NOT NULL REFERENCES sandbox_hosts(id), host_incarnation BIGINT NOT NULL, fence_epoch BIGINT NOT NULL, sequence BIGINT NOT NULL, kind TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}', state TEXT NOT NULL CHECK(state IN('pending','delivered','acknowledged','succeeded','failed','superseded')), attempt INT NOT NULL DEFAULT 0, result JSONB NOT NULL DEFAULT '{}', failure_code TEXT NOT NULL DEFAULT '', failure_message TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(host_id,host_incarnation,sequence));
CREATE TABLE IF NOT EXISTS sandbox_snapshot_artifacts (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, snapshot_id TEXT NOT NULL, artifact_type TEXT NOT NULL CHECK(artifact_type IN('memory.full','vmstate.full','drive.full')), drive_id TEXT, object_ref TEXT NOT NULL, object_version TEXT NOT NULL, logical_size BIGINT NOT NULL, cipher_size BIGINT NOT NULL, logical_sha256 TEXT NOT NULL, cipher_sha256 TEXT NOT NULL, state TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY(snapshot_id,tenant_id) REFERENCES sandbox_snapshots(id,tenant_id) ON DELETE CASCADE, UNIQUE(snapshot_id,artifact_type,drive_id));
CREATE TABLE IF NOT EXISTS sandbox_snapshot_uploads (id TEXT PRIMARY KEY, artifact_id TEXT NOT NULL REFERENCES sandbox_snapshot_artifacts(id) ON DELETE CASCADE, upload_id TEXT NOT NULL, part_size BIGINT NOT NULL, part_count INT NOT NULL, uploaded_parts JSONB NOT NULL DEFAULT '[]', state TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, attempts INT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sandbox_events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, sandbox_id TEXT, recipe_version_id TEXT, operation_id TEXT, snapshot_id TEXT, sequence BIGINT NOT NULL, type TEXT NOT NULL, source TEXT NOT NULL, level TEXT NOT NULL DEFAULT 'info', message TEXT NOT NULL, details JSONB NOT NULL DEFAULT '{}', generation BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK((sandbox_id IS NOT NULL)::int+(recipe_version_id IS NOT NULL)::int=1)); CREATE UNIQUE INDEX IF NOT EXISTS sandbox_event_sequence ON sandbox_events(sandbox_id,sequence) WHERE sandbox_id IS NOT NULL; CREATE UNIQUE INDEX IF NOT EXISTS recipe_event_sequence ON sandbox_events(recipe_version_id,sequence) WHERE recipe_version_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS sandbox_logs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, sandbox_id TEXT, recipe_version_id TEXT, operation_id TEXT, sequence BIGINT NOT NULL, source TEXT NOT NULL, stream TEXT NOT NULL, message TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ NOT NULL, CHECK((sandbox_id IS NOT NULL)::int+(recipe_version_id IS NOT NULL)::int=1));
CREATE TABLE IF NOT EXISTS sandbox_outbox (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES sandbox_events(id) ON DELETE CASCADE, topic TEXT NOT NULL, payload JSONB NOT NULL, attempt INT NOT NULL DEFAULT 0, available_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ, last_error TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS sandbox_capacity_actions (id TEXT PRIMARY KEY, pool_id TEXT NOT NULL REFERENCES sandbox_host_pools(id), reason TEXT NOT NULL, observed_hosts INT NOT NULL, target_hosts INT NOT NULL, status TEXT NOT NULL, request_fingerprint TEXT NOT NULL, provider_result JSONB NOT NULL DEFAULT '{}', attempts INT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(pool_id,request_fingerprint));
-- Guard immutable records and snapshot recovery metadata even if a future caller bypasses stores.
CREATE OR REPLACE FUNCTION sandbox_profile_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.id<>OLD.id OR NEW.profile_family<>OLD.profile_family OR NEW.name<>OLD.name OR NEW.version<>OLD.version OR NEW.vcpu<>OLD.vcpu OR NEW.memory_mb<>OLD.memory_mb OR NEW.mutable_disk_layout<>OLD.mutable_disk_layout OR NEW.runtime_overhead<>OLD.runtime_overhead OR NEW.machine_config<>OLD.machine_config OR NEW.device_topology<>OLD.device_topology OR NEW.architecture_constraints<>OLD.architecture_constraints OR NEW.canonical_document<>OLD.canonical_document OR NEW.document_digest<>OLD.document_digest THEN RAISE EXCEPTION 'sandbox profile version is immutable'; END IF;
 IF OLD.status='retired' AND NEW.status<>'retired' THEN RAISE EXCEPTION 'sandbox profile retirement is monotonic'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS sandbox_profile_immutable_trigger ON sandbox_profile_versions; CREATE TRIGGER sandbox_profile_immutable_trigger BEFORE UPDATE ON sandbox_profile_versions FOR EACH ROW EXECUTE FUNCTION sandbox_profile_immutable();
CREATE OR REPLACE FUNCTION sandbox_recipe_version_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.recipe_id<>OLD.recipe_id OR NEW.version_number<>OLD.version_number OR NEW.schema_version<>OLD.schema_version OR NEW.document<>OLD.document OR NEW.document_digest<>OLD.document_digest OR NEW.resolved_base_digest<>OLD.resolved_base_digest THEN RAISE EXCEPTION 'sandbox recipe version is immutable'; END IF; IF OLD.status IN ('ready','retired') AND NEW.status<>OLD.status THEN RAISE EXCEPTION 'ready or retired recipe version cannot change'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS sandbox_recipe_version_immutable_trigger ON sandbox_image_recipe_versions; CREATE TRIGGER sandbox_recipe_version_immutable_trigger BEFORE UPDATE ON sandbox_image_recipe_versions FOR EACH ROW EXECUTE FUNCTION sandbox_recipe_version_immutable();
CREATE OR REPLACE FUNCTION sandbox_recipe_artifact_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.recipe_version_id<>OLD.recipe_version_id OR NEW.profile_version_id<>OLD.profile_version_id OR (OLD.status='ready' AND (NEW.artifact_ref<>OLD.artifact_ref OR NEW.artifact_digest<>OLD.artifact_digest OR NEW.artifact_size<>OLD.artifact_size OR NEW.vm_restore_descriptor_digest<>OLD.vm_restore_descriptor_digest OR NEW.status<>OLD.status)) THEN RAISE EXCEPTION 'ready recipe artifact is immutable'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS sandbox_recipe_artifact_immutable_trigger ON sandbox_image_recipe_profile_artifacts; CREATE TRIGGER sandbox_recipe_artifact_immutable_trigger BEFORE UPDATE ON sandbox_image_recipe_profile_artifacts FOR EACH ROW EXECUTE FUNCTION sandbox_recipe_artifact_immutable();
CREATE OR REPLACE FUNCTION sandbox_snapshot_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.state='ready' AND (NEW.id<>OLD.id OR NEW.tenant_id<>OLD.tenant_id OR NEW.sandbox_id<>OLD.sandbox_id OR NEW.operation_id<>OLD.operation_id OR NEW.generation<>OLD.generation OR NEW.lineage_id<>OLD.lineage_id OR NEW.source_host_compatibility_key<>OLD.source_host_compatibility_key OR NEW.vm_restore_descriptor_digest<>OLD.vm_restore_descriptor_digest OR NEW.snapshot_compatibility_key<>OLD.snapshot_compatibility_key OR NEW.manifest<>OLD.manifest OR NEW.manifest_checksum<>OLD.manifest_checksum OR NEW.wrapped_data_key<>OLD.wrapped_data_key OR NEW.encryption_context_digest<>OLD.encryption_context_digest OR NEW.total_bytes<>OLD.total_bytes OR NEW.state<>OLD.state) THEN RAISE EXCEPTION 'ready snapshot is immutable'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS sandbox_snapshot_immutable_trigger ON sandbox_snapshots; CREATE TRIGGER sandbox_snapshot_immutable_trigger BEFORE UPDATE ON sandbox_snapshots FOR EACH ROW EXECUTE FUNCTION sandbox_snapshot_immutable();
ALTER TABLE sandbox_snapshots DROP CONSTRAINT IF EXISTS sandbox_snapshots_operation_sandbox_fk;
ALTER TABLE sandbox_snapshots ADD CONSTRAINT sandbox_snapshots_operation_sandbox_fk FOREIGN KEY(operation_id,tenant_id,sandbox_id) REFERENCES sandbox_operations(id,tenant_id,sandbox_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sandbox_operations DROP CONSTRAINT IF EXISTS sandbox_operations_snapshot_sandbox_fk;
ALTER TABLE sandbox_operations ADD CONSTRAINT sandbox_operations_snapshot_sandbox_fk FOREIGN KEY(snapshot_id,tenant_id,sandbox_id) REFERENCES sandbox_snapshots(id,tenant_id,sandbox_id) DEFERRABLE INITIALLY DEFERRED;

-- Every sandbox-scoped reference carries both tenant and sandbox identity. This
-- keeps a valid ID from another sandbox or tenant from becoming an authority.
CREATE UNIQUE INDEX IF NOT EXISTS sandbox_allocations_id_tenant_sandbox_unique ON sandbox_allocations(id,tenant_id,sandbox_id);
CREATE UNIQUE INDEX IF NOT EXISTS sandbox_allocations_identity_unique ON sandbox_allocations(id,tenant_id,sandbox_id,host_id,host_incarnation,fence_epoch);

ALTER TABLE sandboxes DROP CONSTRAINT IF EXISTS sandboxes_latest_snapshot_fk;
ALTER TABLE sandboxes ADD CONSTRAINT sandboxes_latest_snapshot_fk FOREIGN KEY(latest_snapshot_id,tenant_id,id) REFERENCES sandbox_snapshots(id,tenant_id,sandbox_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sandboxes DROP CONSTRAINT IF EXISTS sandboxes_current_allocation_ownership_fk;
ALTER TABLE sandboxes ADD CONSTRAINT sandboxes_current_allocation_ownership_fk FOREIGN KEY(current_allocation_id,tenant_id,id) REFERENCES sandbox_allocations(id,tenant_id,sandbox_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE sandbox_snapshots DROP CONSTRAINT IF EXISTS sandbox_snapshots_allocation_ownership_fk;
ALTER TABLE sandbox_snapshots ADD CONSTRAINT sandbox_snapshots_allocation_ownership_fk FOREIGN KEY(allocation_id,tenant_id,sandbox_id) REFERENCES sandbox_allocations(id,tenant_id,sandbox_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sandbox_snapshots DROP CONSTRAINT IF EXISTS sandbox_snapshots_lineage_source_fk;
ALTER TABLE sandbox_snapshots ADD CONSTRAINT sandbox_snapshots_lineage_source_fk FOREIGN KEY(lineage_id,source_host_compatibility_key) REFERENCES sandbox_host_lineages(id,host_compatibility_key);

ALTER TABLE sandbox_commands DROP CONSTRAINT IF EXISTS sandbox_commands_operation_id_fkey;
ALTER TABLE sandbox_commands DROP CONSTRAINT IF EXISTS sandbox_commands_allocation_id_fkey;
ALTER TABLE sandbox_commands DROP CONSTRAINT IF EXISTS sandbox_commands_operation_ownership_fk;
ALTER TABLE sandbox_commands ADD CONSTRAINT sandbox_commands_operation_ownership_fk FOREIGN KEY(operation_id,tenant_id,sandbox_id) REFERENCES sandbox_operations(id,tenant_id,sandbox_id) ON DELETE CASCADE;
ALTER TABLE sandbox_commands DROP CONSTRAINT IF EXISTS sandbox_commands_allocation_ownership_fk;
ALTER TABLE sandbox_commands ADD CONSTRAINT sandbox_commands_allocation_ownership_fk FOREIGN KEY(allocation_id,tenant_id,sandbox_id,host_id,host_incarnation,fence_epoch) REFERENCES sandbox_allocations(id,tenant_id,sandbox_id,host_id,host_incarnation,fence_epoch);

ALTER TABLE sandbox_events DROP CONSTRAINT IF EXISTS sandbox_events_sandbox_ownership_fk;
ALTER TABLE sandbox_events ADD CONSTRAINT sandbox_events_sandbox_ownership_fk FOREIGN KEY(sandbox_id,tenant_id) REFERENCES sandboxes(id,tenant_id) ON DELETE CASCADE;
ALTER TABLE sandbox_events DROP CONSTRAINT IF EXISTS sandbox_events_recipe_ownership_fk;
ALTER TABLE sandbox_events ADD CONSTRAINT sandbox_events_recipe_ownership_fk FOREIGN KEY(recipe_version_id,tenant_id) REFERENCES sandbox_image_recipe_versions(id,tenant_id) ON DELETE CASCADE;
ALTER TABLE sandbox_events DROP CONSTRAINT IF EXISTS sandbox_events_operation_tenant_fk;
ALTER TABLE sandbox_events ADD CONSTRAINT sandbox_events_operation_tenant_fk FOREIGN KEY(operation_id,tenant_id) REFERENCES sandbox_operations(id,tenant_id) ON DELETE CASCADE;
ALTER TABLE sandbox_events DROP CONSTRAINT IF EXISTS sandbox_events_operation_ownership_fk;
ALTER TABLE sandbox_events ADD CONSTRAINT sandbox_events_operation_ownership_fk FOREIGN KEY(operation_id,tenant_id,sandbox_id) REFERENCES sandbox_operations(id,tenant_id,sandbox_id) ON DELETE CASCADE;
ALTER TABLE sandbox_events DROP CONSTRAINT IF EXISTS sandbox_events_snapshot_ownership_fk;
ALTER TABLE sandbox_events ADD CONSTRAINT sandbox_events_snapshot_ownership_fk FOREIGN KEY(snapshot_id,tenant_id,sandbox_id) REFERENCES sandbox_snapshots(id,tenant_id,sandbox_id) ON DELETE CASCADE;

ALTER TABLE sandbox_logs DROP CONSTRAINT IF EXISTS sandbox_logs_sandbox_ownership_fk;
ALTER TABLE sandbox_logs ADD CONSTRAINT sandbox_logs_sandbox_ownership_fk FOREIGN KEY(sandbox_id,tenant_id) REFERENCES sandboxes(id,tenant_id) ON DELETE CASCADE;
ALTER TABLE sandbox_logs DROP CONSTRAINT IF EXISTS sandbox_logs_recipe_ownership_fk;
ALTER TABLE sandbox_logs ADD CONSTRAINT sandbox_logs_recipe_ownership_fk FOREIGN KEY(recipe_version_id,tenant_id) REFERENCES sandbox_image_recipe_versions(id,tenant_id) ON DELETE CASCADE;
ALTER TABLE sandbox_logs DROP CONSTRAINT IF EXISTS sandbox_logs_operation_tenant_fk;
ALTER TABLE sandbox_logs ADD CONSTRAINT sandbox_logs_operation_tenant_fk FOREIGN KEY(operation_id,tenant_id) REFERENCES sandbox_operations(id,tenant_id) ON DELETE CASCADE;
ALTER TABLE sandbox_logs DROP CONSTRAINT IF EXISTS sandbox_logs_operation_ownership_fk;
ALTER TABLE sandbox_logs ADD CONSTRAINT sandbox_logs_operation_ownership_fk FOREIGN KEY(operation_id,tenant_id,sandbox_id) REFERENCES sandbox_operations(id,tenant_id,sandbox_id) ON DELETE CASCADE;

-- Snapshot recovery identity is fixed at creation. Lifecycle state may only
-- advance; a failure, ready time, or deletion time can be recorded once and
-- never cleared or rolled back.
CREATE OR REPLACE FUNCTION sandbox_snapshot_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.id IS DISTINCT FROM OLD.id OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id OR NEW.sandbox_id IS DISTINCT FROM OLD.sandbox_id OR NEW.allocation_id IS DISTINCT FROM OLD.allocation_id OR NEW.operation_id IS DISTINCT FROM OLD.operation_id OR NEW.generation IS DISTINCT FROM OLD.generation OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.lineage_id IS DISTINCT FROM OLD.lineage_id OR NEW.source_host_compatibility_key IS DISTINCT FROM OLD.source_host_compatibility_key OR NEW.vm_restore_descriptor_digest IS DISTINCT FROM OLD.vm_restore_descriptor_digest OR NEW.snapshot_compatibility_key IS DISTINCT FROM OLD.snapshot_compatibility_key OR NEW.manifest_version IS DISTINCT FROM OLD.manifest_version OR NEW.manifest IS DISTINCT FROM OLD.manifest OR NEW.manifest_checksum IS DISTINCT FROM OLD.manifest_checksum OR NEW.wrapped_data_key IS DISTINCT FROM OLD.wrapped_data_key OR NEW.encryption_context_digest IS DISTINCT FROM OLD.encryption_context_digest OR NEW.total_bytes IS DISTINCT FROM OLD.total_bytes THEN RAISE EXCEPTION 'snapshot recovery identity is immutable'; END IF;
 IF NOT ((OLD.state='requested' AND NEW.state IN('requested','uploading','failed','deleting')) OR (OLD.state='uploading' AND NEW.state IN('uploading','verifying','failed','deleting')) OR (OLD.state='verifying' AND NEW.state IN('verifying','ready','failed','deleting')) OR (OLD.state='ready' AND NEW.state IN('ready','deleting')) OR (OLD.state='failed' AND NEW.state IN('failed','deleting')) OR (OLD.state='deleting' AND NEW.state IN('deleting','deleted')) OR (OLD.state='deleted' AND NEW.state='deleted')) THEN RAISE EXCEPTION 'snapshot state cannot move backwards'; END IF;
 IF OLD.ready_at IS NOT NULL AND NEW.ready_at IS DISTINCT FROM OLD.ready_at THEN RAISE EXCEPTION 'snapshot readiness is immutable once recorded'; END IF;
 IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN RAISE EXCEPTION 'snapshot deletion is immutable once recorded'; END IF;
 IF NEW.state='ready' AND NEW.ready_at IS NULL THEN RAISE EXCEPTION 'ready snapshot requires ready_at'; END IF;
 IF NEW.state='deleted' AND NEW.deleted_at IS NULL THEN RAISE EXCEPTION 'deleted snapshot requires deleted_at'; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS sandbox_snapshot_immutable_trigger ON sandbox_snapshots;
CREATE TRIGGER sandbox_snapshot_immutable_trigger BEFORE UPDATE ON sandbox_snapshots FOR EACH ROW EXECUTE FUNCTION sandbox_snapshot_immutable();
