-- Allocation lease tokens are generated by the control plane, returned only in
-- the fenced command payload, and compared by SHA-256 on every renewal.
ALTER TABLE sandbox_allocations ADD COLUMN IF NOT EXISTS lease_token_envelope TEXT NOT NULL DEFAULT '';

-- Snapshot recovery identity is immutable from creation, but the manifest and
-- artifact completion fields are intentionally populated while uploading. Once
-- ready, every field becomes immutable except deletion lifecycle metadata.
CREATE OR REPLACE FUNCTION sandbox_snapshot_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.id IS DISTINCT FROM OLD.id OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id OR NEW.sandbox_id IS DISTINCT FROM OLD.sandbox_id OR NEW.allocation_id IS DISTINCT FROM OLD.allocation_id OR NEW.operation_id IS DISTINCT FROM OLD.operation_id OR NEW.generation IS DISTINCT FROM OLD.generation OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.lineage_id IS DISTINCT FROM OLD.lineage_id OR NEW.source_host_compatibility_key IS DISTINCT FROM OLD.source_host_compatibility_key OR NEW.vm_restore_descriptor_digest IS DISTINCT FROM OLD.vm_restore_descriptor_digest OR NEW.snapshot_compatibility_key IS DISTINCT FROM OLD.snapshot_compatibility_key OR NEW.manifest_version IS DISTINCT FROM OLD.manifest_version THEN RAISE EXCEPTION 'snapshot recovery identity is immutable'; END IF;
 IF OLD.state='ready' AND (NEW.manifest IS DISTINCT FROM OLD.manifest OR NEW.manifest_checksum IS DISTINCT FROM OLD.manifest_checksum OR NEW.wrapped_data_key IS DISTINCT FROM OLD.wrapped_data_key OR NEW.encryption_context_digest IS DISTINCT FROM OLD.encryption_context_digest OR NEW.total_bytes IS DISTINCT FROM OLD.total_bytes) THEN RAISE EXCEPTION 'ready snapshot content is immutable'; END IF;
 IF NOT ((OLD.state='requested' AND NEW.state IN('requested','uploading','failed','deleting')) OR (OLD.state='uploading' AND NEW.state IN('uploading','verifying','failed','deleting')) OR (OLD.state='verifying' AND NEW.state IN('verifying','ready','failed','deleting')) OR (OLD.state='ready' AND NEW.state IN('ready','deleting')) OR (OLD.state='failed' AND NEW.state IN('failed','deleting')) OR (OLD.state='deleting' AND NEW.state IN('deleting','deleted')) OR (OLD.state='deleted' AND NEW.state='deleted')) THEN RAISE EXCEPTION 'snapshot state cannot move backwards'; END IF;
 IF OLD.ready_at IS NOT NULL AND NEW.ready_at IS DISTINCT FROM OLD.ready_at THEN RAISE EXCEPTION 'snapshot readiness is immutable once recorded'; END IF;
 IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN RAISE EXCEPTION 'snapshot deletion is immutable once recorded'; END IF;
 IF NEW.state='ready' AND NEW.ready_at IS NULL THEN RAISE EXCEPTION 'ready snapshot requires ready_at'; END IF;
 IF NEW.state='deleted' AND NEW.deleted_at IS NULL THEN RAISE EXCEPTION 'deleted snapshot requires deleted_at'; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS sandbox_snapshot_immutable_trigger ON sandbox_snapshots;
CREATE TRIGGER sandbox_snapshot_immutable_trigger BEFORE UPDATE ON sandbox_snapshots FOR EACH ROW EXECUTE FUNCTION sandbox_snapshot_immutable();
